### PR TITLE
Μain refactoring & some random fixes

### LINKED ISSUE #255: Event Flags dialog crashes the emulator
Trying to open the Event Flags debug dialog instantly crashes the emulator.

### PR DESCRIPTION
**Pull request by VelocityRa**
Some needed `main()`, `host` and `imgui` impl. refactoring and a few minor fixes.
Resolves #255.

### Note to devs
Please use `log_hex()` to format hex strings from now on, with `{}` as the format string. It outputs unsigned hex strings in the format of `0xD34DB33F`, with `0` padding according to size of input type.
This is so that we finally have a standardized way to print them.

### CODE REVIEW

**Comment by VelocityRa** [comment]
Ready for review.

File: src/emulator/gui/include/gui/imgui_impl.h [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+// GNU General Public License for more details.
+//
+// You should have received a copy of the GNU General Public License along
+// with this program; if not, write to the Free Software Foundation, Inc.,
+// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
+
+#pragma once
+
+#include <host/state.h>
```
Comment (petmac) [inline src/emulator/gui/include/gui/imgui_impl.h]: Would it be possible to forward declare what we need rather than pull in all the host state?

File: src/emulator/gui/include/gui/imgui_impl.h [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+
+#include <glutil/gl.h>
+
+// clang-format off
```
Comment (petmac) [inline src/emulator/gui/include/gui/imgui_impl.h]: I've seen this in a few places. I'm not saying it's wrong, but why is it needed?

Side note: My preference is to put our headers before 3rd party ones (separated by a newline) as this should encourage ours to be self-contained and not rely on other headers coming first.

File: src/emulator/host/src/app.cpp [hunk 3]
```diff
@@ -235,3 +247,74 @@ bool load_app(Ptr<const void> &entry_point, HostState &host, const std::wstring
...
+
+    return Success;
+}
+
+void no_fb_fallback(HostState &host, GLuint *fb_texture_id) {
+    glGenTextures(1, fb_texture_id);
+    glClearColor(1.0, 0.0, 0.5, 1.0);
+    glClearDepth(1.0f);
+    glViewport(0, 0, host.display.image_size.width, host.display.image_size.height);
+    glMatrixMode(GL_PROJECTION);
```
Comment (petmac) [inline src/emulator/host/src/app.cpp]: These matrix functions aren't in OpenGL 4.1 Core -- we only use shaders so they're not necessary.

File: src/emulator/main.cpp [hunk 4]
```diff
@@ -137,99 +97,31 @@ int main(int argc, char *argv[]) {
...
-        return RunThreadFailed;
-    }
-
-    GLuint TextureID = 0;
-    host.t1 = SDL_GetTicks();
+    GLuint fb_texture_id = 0;
+    host.sdl_ticks = SDL_GetTicks();
     while (handle_events(host)) {
-        if (!TextureID) {
-            glGenTextures(1, &TextureID);
```
Comment (petmac) [inline src/emulator/main.cpp]: This looks like initialisation code which could just be moved up. I don't think it'll be possible to not have a texture.

File: src/emulator/gui/include/gui/imgui_impl.h (hunk 2 above)
Comment (VelocityRa) [reply src/emulator/gui/include/gui/imgui_impl.h]: It's needed because imgui.h need to be included before any other imgui-related files are included (else you get a compile error) and clang-format changes their order without this.

File: src/emulator/gui/include/gui/imgui_impl.h (hunk 1 above)
Comment (VelocityRa) [reply src/emulator/gui/include/gui/imgui_impl.h]: `WindowPtr` is a `typedef` to `std::shared_ptr<SDL_Window>`, we can't forward declare it in a maintainable way afaik.

File: src/emulator/gui/include/gui/imgui_impl.h (hunk 2 above)
Comment (VelocityRa) [reply src/emulator/gui/include/gui/imgui_impl.h]: And I definitely agree with the side note, I'll change their order.

File: src/emulator/host/src/app.cpp (hunk 3 above)
Comment (VelocityRa) [reply src/emulator/host/src/app.cpp]: I removed those, `glLoadIdentity` and `glOrtho`.

File: src/emulator/main.cpp (hunk 4 above)
Comment (VelocityRa) [reply src/emulator/main.cpp]: This was meant to be a purely-refactoring PR and I'm not sure if that's the case. Surely it's like this for a reason?

Comment (petmac) [reply src/emulator/main.cpp]: No problem.
