### PR TITLE
Small fixes

### LINKED ISSUE #1037: cmake: generate project erreur
Last cmake version working with it is 3.17.5 
After update cmake on last version (3.19), i get error on generate project

image

# Issue:
Information by @1whatleytay 
>so as for ext-boost
b2 seems to prefix library names with lib for windows
and as of 3.19 cmake will absolutely not pick up on this
you may have to delete the prefixed lib in ext-boost for the following libraries
image
since we copy them we can probably rename them in the batch script
this is a workaround for now though, the root of the problem is probably somewhere in our configuration or is a boost/cmake bug

### PR DESCRIPTION
**Pull request by bookmist**
Different small fixes.
cmake: improved boost search  - fix #1037 can't be checked by CI. need manual check on linux and macos
kernel: Clear TLS on first get - not a good fix, all TLS shoul be rewritten, but now it make possible to run libUlt.suprx used in some games
modules/sceLibKernel: _sceKernelGetThreadInfo. fix stack pointer - looks like misprint, and also fix libUlt.suprx

Mostly help to run "Ar nosurge Plus - Ode to an Unborn Star" [PCSE00707]

### CODE REVIEW

**Comment by Zangetsu38** [comment]
Run format for all commit all time 😁

File: vita3k/kernel/src/kernel.cpp [hunk 1]
```diff
@@ -55,8 +53,9 @@ Ptr<Ptr<void>> get_thread_tls_addr(KernelState &kernel, MemState &mem, SceUID th
 
         *address.get(mem) = new_tls;
         slot_to_address.insert(SlotToAddress::value_type(key, address));
-        return address;
     }
+    *(address.get(mem)) = 0;
```
Comment (frangarcj) [inline vita3k/kernel/src/kernel.cpp:57]: Why this?

Comment (bookmist) [reply vita3k/kernel/src/kernel.cpp:57]: cause "Ar nosurge Plus - Ode to an Unborn Star" [PCSE00707] expect pointer to 0 on first run of sceKernelGetTLSAddr(43)
It was a fast hack. Going to rewrite it properly in a few days

Comment (bookmist) [reply vita3k/kernel/src/kernel.cpp]: I rewrote it properly.
@frangarcj i've seen your last commit in get_thread_tls_addr What you were trying to do? what game you were trying to run? Sorry, if i look rude, my english is not good enough. I want to know, on what game i can run regression test after this further changes.

**Review by frangarcj — APPROVED** [review]
