### PR TITLE
[libRtc/libKernel] Fix clock implementation

### LINKED ISSUE #56: Clock is wrong on Windows
Affected functions are sceKernelGetProcessTime* functions and sceRtcGetTick function.
This causes ticks based homebrews to stall a lot of time for nothing (that's why Network PR has issues on Windows for example).

### PR DESCRIPTION
**Pull request by VelocityRa**
vitaQuake multiplayer works with this + #39 
Resolves #56

### CODE REVIEW

File: src/emulator/modules/SceRtc/src/SceRtcUser.cpp [hunk 1]
```diff
@@ -68,8 +68,13 @@ EXPORT(int, sceRtcGetCurrentNetworkTick) {
 EXPORT(int, sceRtcGetCurrentTick, SceRtcTick *tick) {
     assert(tick != nullptr);
```
Comment (Rinnegatamante) [inline src/emulator/modules/SceRtc/src/SceRtcUser.cpp]: This should be replaced with error();

File: src/emulator/host/include/host/rtc.h [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
+
+#pragma once
+
+#include <host/state.h>
+
+#include <chrono>
+#include <cstdint>
+
+#define VITA_CLOCKS_PER_SEC 1000000
```
Comment (petmac) [inline src/emulator/host/include/host/rtc.h]: I'd move as much of this as possible into `rtc.cpp`, as it doesn't need to be in a header or inlined.

Comment (VelocityRa) [reply src/emulator/host/include/host/rtc.h]: Only reason I didn't is because with the current code structure - as far as I understand it - it would be in `host.cpp` instead of an `rtc.cpp`.
